name: parallel_universe_weather
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  # Load xarray and cfgrib
  - xarray>=2022.12
  - cfgrib
  - netcdf4
  - dask >=2022.12

  - geopandas>=0.11
  - cartopy>=0.21
  - shapely>=2.0.0
  - seaborn>=0.11
  - metpy>=1.5
# install notebook packages
  - jupyter
  - notebook
  - pip
  - pip:
    - ipympl